### ISSUE TITLE
Show user their property ID?

### ISSUE THREAD

**Issue by zo0o0ot** [dhmncivichacks/isitrecycling#7]
This is a selfish request, I was seeing if I could get the user to search for their property ID for the Appleton Pebble app using the is it recycling web app.  My first config step was to have users manually enter their properly ID.  I see that it is visible from the API calls, but I'm pretty sure I shouldn't require users to inpsect your webapp network calls to enter their property config info.

**Comment by chrisjaure** [comment]
Lol, how about I log the property ID or add some secret konami code to show it?

**Comment by zo0o0ot** [comment]
Works for me.

**Comment by chrisjaure** [comment]
Fixed in 79321dab56ef94a82423129250fb764423a53efa
